language: php

php:
  - 7.4
  - 8.0

before_install:
  - travis_retry composer dump-auto -o
  - travis_retry composer self-update

install:
  - travis_retry composer update --no-interaction --prefer-dist --prefer-stable

script:
  - vendor/bin/phpunit